### PR TITLE
Task1 and Task2 using Flutter

### PR DESCRIPTION
**Pull request by rishabh-0904**
With due respect,
I have done Task1 and Task2 using flutter and will do remaining task next.
Consider this Pull Request as a beginner PR.

### CODE REVIEW

**Comment by Khali851999** [comment]
Add Screenshots

**Review by Khali851999 — CHANGES_REQUESTED** [review]
Add Screenshots

**Comment by rishabh-0904** [comment]
I have added screenshots now.

**Review by Khali851999 — CHANGES_REQUESTED** [review]
image

 ADD COMPLETED TASK SS LIKE THIS

**Pull request merged**
